import { localAI } from './local-ai';
const DEFAULT_API='http://localhost:8000';
const out=document.getElementById('out')!;let title='';let url='';let token=localStorage.getItem('sa_access')||'';
const apiInput=document.getElementById('api') as HTMLInputElement; apiInput.value=localStorage.getItem('sa_api')||DEFAULT_API;
chrome.tabs.query({active:true,currentWindow:true},tabs=>{title=tabs[0]?.title||'';url=tabs[0]?.url||'';(document.getElementById('page')!).textContent=title;(document.getElementById('currentUrl')!).textContent=url});
function api(){return apiInput.value.replace(/\/$/,'')||DEFAULT_API}
async function req(path:string,opt:RequestInit={}){localStorage.setItem('sa_api',api());const h=new Headers(opt.headers||{});h.set('Content-Type','application/json');if(token)h.set('Authorization',`Bearer ${token}`);const r=await fetch(api()+path,{...opt,headers:h});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.detail||'Request failed');return j}
(document.getElementById('login')!).onclick=async()=>{try{const x=await req('/api/auth/login',{method:'POST',body:JSON.stringify({email:(document.getElementById('email') as HTMLInputElement).value,password:(document.getElementById('password') as HTMLInputElement).value})});token=x.access_token;localStorage.setItem('sa_access',token);out.innerHTML='<span class="ok">Signed in.</span>'}catch(e:any){out.innerHTML='<span class="error">'+e.message+'</span>'}};
(document.getElementById('add')!).onclick=async()=>{try{let name=title; try { const normalized=await localAI('Extract the concise product name from this page title. Return only the product name and do not invent details: '+title); if(normalized) name=normalized; } catch {} await req('/api/items',{method:'POST',body:JSON.stringify({name})});out.innerHTML='<span class="ok">Added to To-Buy.</span>'}catch(e:any){out.innerHTML='<span class="error">'+e.message+'</span>'}};
(document.getElementById('monitor')!).onclick=async()=>{try{const x=await req('/api/products/url-analyze',{method:'POST',body:JSON.stringify({url,monitor:true})});out.innerHTML='<span class="ok">Monitoring started for '+x.product.name+'.</span>'}catch(e:any){out.innerHTML='<span class="error">'+e.message+'</span>'}};
(document.getElementById('ingest')!).onclick=async()=>{try{const x=await req('/api/products/url-analyze',{method:'POST',body:JSON.stringify({url,monitor:false})});out.innerHTML='<span class="ok">Verified '+x.product.name+'. Comparison ready.</span>'}catch(e:any){out.innerHTML='<span class="error">'+e.message+'</span>'}};
(document.getElementById('batch')!).onclick=async()=>{try{const urls=(document.getElementById('urls') as HTMLTextAreaElement).value.split(/\n|,/).map(x=>x.trim()).filter(Boolean).map(url=>({url,monitor:false}));const todo_items=(document.getElementById('items') as HTMLTextAreaElement).value.split(/\n/).map(x=>x.trim()).filter(Boolean);const x=await req('/api/batch/process',{method:'POST',body:JSON.stringify({urls,todo_items})});out.innerHTML='<span class="ok">Processed '+x.summary.urls_succeeded+' verified URLs and '+x.summary.todo_created+' To-Buy items.</span>'; }catch(e:any){out.innerHTML='<span class="error">'+e.message+'</span>'}};
