from datetime import datetime,timezone
from sqlalchemy import String,Integer,Float,Boolean,DateTime,Text,ForeignKey,UniqueConstraint
from sqlalchemy.orm import Mapped,mapped_column
from .db import Base

def now(): return datetime.now(timezone.utc)
class User(Base):
 __tablename__='users'; id:Mapped[int]=mapped_column(primary_key=True); email:Mapped[str]=mapped_column(String(255),unique=True,index=True); password_hash:Mapped[str]=mapped_column(String(255)); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now); disabled:Mapped[bool]=mapped_column(Boolean,default=False)
class RefreshToken(Base):
 __tablename__='refresh_tokens'; id:Mapped[int]=mapped_column(primary_key=True); user_id:Mapped[int]=mapped_column(ForeignKey('users.id'),index=True); token_hash:Mapped[str]=mapped_column(String(128),unique=True); expires_at:Mapped[datetime]=mapped_column(DateTime(timezone=True)); revoked:Mapped[bool]=mapped_column(Boolean,default=False); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class UserPreference(Base):
 __tablename__='user_preferences'; id:Mapped[int]=mapped_column(primary_key=True); user_id:Mapped[int]=mapped_column(ForeignKey('users.id'),unique=True); preferred_brands:Mapped[str]=mapped_column(Text,default=''); avoided_brands:Mapped[str]=mapped_column(Text,default=''); preferred_stores:Mapped[str]=mapped_column(Text,default=''); min_seller_rating:Mapped[float]=mapped_column(Float,default=4); warranty_required:Mapped[bool]=mapped_column(Boolean,default=False); global_auto_buy:Mapped[bool]=mapped_column(Boolean,default=False); global_max_order:Mapped[float]=mapped_column(Float,default=5000); monthly_max:Mapped[float]=mapped_column(Float,default=20000); emergency_stop:Mapped[bool]=mapped_column(Boolean,default=False); custom_ai_enabled:Mapped[bool]=mapped_column(Boolean,default=False); custom_ai_provider:Mapped[str]=mapped_column(String(50),default='openai'); custom_ai_base_url:Mapped[str]=mapped_column(String(500),default='https://api.openai.com/v1'); custom_ai_api_key:Mapped[str]=mapped_column(Text,default=''); custom_ai_model:Mapped[str]=mapped_column(String(120),default='gpt-4o-mini')
class ShoppingList(Base):
 __tablename__='shopping_lists'; id:Mapped[int]=mapped_column(primary_key=True); user_id:Mapped[int]=mapped_column(ForeignKey('users.id'),index=True); name:Mapped[str]=mapped_column(String(120),default='My Shopping List')
class Product(Base):
 __tablename__='products'; id:Mapped[int]=mapped_column(primary_key=True); name:Mapped[str]=mapped_column(String(255)); brand:Mapped[str]=mapped_column(String(100),default=''); model:Mapped[str]=mapped_column(String(120),default=''); category:Mapped[str]=mapped_column(String(100),default=''); variant:Mapped[str]=mapped_column(String(255),default=''); gtin:Mapped[str]=mapped_column(String(80),default=''); specs:Mapped[str]=mapped_column(Text,default='')
class Store(Base):
 __tablename__='stores'; id:Mapped[int]=mapped_column(primary_key=True); name:Mapped[str]=mapped_column(String(120),unique=True); base_url:Mapped[str]=mapped_column(String(500),default=''); search_supported:Mapped[bool]=mapped_column(Boolean,default=False); price_supported:Mapped[bool]=mapped_column(Boolean,default=False); stock_supported:Mapped[bool]=mapped_column(Boolean,default=False); checkout_supported:Mapped[bool]=mapped_column(Boolean,default=False); automation_allowed:Mapped[bool]=mapped_column(Boolean,default=False)
class Seller(Base):
 __tablename__='sellers'; id:Mapped[int]=mapped_column(primary_key=True); store_id:Mapped[int]=mapped_column(ForeignKey('stores.id')); name:Mapped[str]=mapped_column(String(160)); rating:Mapped[float]=mapped_column(Float,default=0)
class StoreListing(Base):
 __tablename__='store_listings'; id:Mapped[int]=mapped_column(primary_key=True); product_id:Mapped[int]=mapped_column(ForeignKey('products.id')); store_id:Mapped[int]=mapped_column(ForeignKey('stores.id')); seller_id:Mapped[int | None]=mapped_column(ForeignKey('sellers.id'),nullable=True); url:Mapped[str]=mapped_column(String(2000)); currency:Mapped[str]=mapped_column(String(8),default='INR'); price:Mapped[float]=mapped_column(Float); delivery:Mapped[float]=mapped_column(Float,default=0); tax:Mapped[float]=mapped_column(Float,default=0); fees:Mapped[float]=mapped_column(Float,default=0); coupon:Mapped[float]=mapped_column(Float,default=0); cashback:Mapped[float]=mapped_column(Float,default=0); stock:Mapped[int]=mapped_column(Integer,default=0); delivery_days:Mapped[int | None]=mapped_column(Integer,nullable=True); warranty:Mapped[str]=mapped_column(String(160),default=''); returns:Mapped[str]=mapped_column(String(160),default=''); condition:Mapped[str]=mapped_column(String(40),default='New'); observed_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class PriceSnapshot(Base):
 __tablename__='price_snapshots'; id:Mapped[int]=mapped_column(primary_key=True); listing_id:Mapped[int]=mapped_column(ForeignKey('store_listings.id'),index=True); price:Mapped[float]=mapped_column(Float); delivery:Mapped[float]=mapped_column(Float); total:Mapped[float]=mapped_column(Float); stock:Mapped[int]=mapped_column(Integer); seller:Mapped[str]=mapped_column(String(160),default=''); timestamp:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class ShoppingItem(Base):
 __tablename__='shopping_items'; id:Mapped[int]=mapped_column(primary_key=True); list_id:Mapped[int]=mapped_column(ForeignKey('shopping_lists.id'),index=True); name:Mapped[str]=mapped_column(String(255)); quantity:Mapped[int]=mapped_column(Integer,default=1); target_price:Mapped[float | None]=mapped_column(Float,nullable=True); max_price:Mapped[float | None]=mapped_column(Float,nullable=True); mode:Mapped[str]=mapped_column(String(30),default='BUY_NOW'); purchase_mode:Mapped[str]=mapped_column(String(30),default='ASK'); status:Mapped[str]=mapped_column(String(30),default='TODO'); product_id:Mapped[int | None]=mapped_column(ForeignKey('products.id'),nullable=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now); completed_at:Mapped[datetime | None]=mapped_column(DateTime(timezone=True),nullable=True)
class MonitoringTask(Base):
 __tablename__='monitoring_tasks'; id:Mapped[int]=mapped_column(primary_key=True); item_id:Mapped[int]=mapped_column(ForeignKey('shopping_items.id'),unique=True); status:Mapped[str]=mapped_column(String(30),default='WATCHING'); interval_minutes:Mapped[int]=mapped_column(Integer,default=360); last_checked:Mapped[datetime | None]=mapped_column(DateTime(timezone=True),nullable=True); next_check:Mapped[datetime | None]=mapped_column(DateTime(timezone=True),nullable=True)
class PriceAlert(Base):
 __tablename__='price_alerts'; id:Mapped[int]=mapped_column(primary_key=True); item_id:Mapped[int]=mapped_column(ForeignKey('shopping_items.id')); alert_type:Mapped[str]=mapped_column(String(60)); message:Mapped[str]=mapped_column(Text); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now); read:Mapped[bool]=mapped_column(Boolean,default=False)
class PurchaseRule(Base):
 __tablename__='purchase_rules'; id:Mapped[int]=mapped_column(primary_key=True); user_id:Mapped[int]=mapped_column(ForeignKey('users.id')); scope:Mapped[str]=mapped_column(String(30)); category:Mapped[str | None]=mapped_column(String(100),nullable=True); product_id:Mapped[int | None]=mapped_column(ForeignKey('products.id'),nullable=True); max_price:Mapped[float | None]=mapped_column(Float,nullable=True); purchase_mode:Mapped[str]=mapped_column(String(30),default='ASK'); enabled:Mapped[bool]=mapped_column(Boolean,default=True)
class Order(Base):
 __tablename__='orders'; id:Mapped[int]=mapped_column(primary_key=True); user_id:Mapped[int]=mapped_column(ForeignKey('users.id')); item_id:Mapped[int]=mapped_column(ForeignKey('shopping_items.id')); listing_id:Mapped[int | None]=mapped_column(ForeignKey('store_listings.id'),nullable=True); product_name:Mapped[str]=mapped_column(String(255)); store:Mapped[str]=mapped_column(String(120)); price:Mapped[float]=mapped_column(Float); observed_price:Mapped[float | None]=mapped_column(Float,nullable=True); status:Mapped[str]=mapped_column(String(30),default='PENDING'); savings:Mapped[float]=mapped_column(Float,default=0); order_number:Mapped[str]=mapped_column(String(100),unique=True); idempotency_key:Mapped[str]=mapped_column(String(100),unique=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class PurchaseTransaction(Base):
 __tablename__='purchase_transactions'; id:Mapped[int]=mapped_column(primary_key=True); order_id:Mapped[int]=mapped_column(ForeignKey('orders.id')); status:Mapped[str]=mapped_column(String(40)); provider_reference:Mapped[str]=mapped_column(String(200),default=''); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class Notification(Base):
 __tablename__='notifications'; id:Mapped[int]=mapped_column(primary_key=True); user_id:Mapped[int]=mapped_column(ForeignKey('users.id')); kind:Mapped[str]=mapped_column(String(60)); title:Mapped[str]=mapped_column(String(200)); message:Mapped[str]=mapped_column(Text); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now); read:Mapped[bool]=mapped_column(Boolean,default=False)
class AgentEvent(Base):
 __tablename__='agent_events'; id:Mapped[int]=mapped_column(primary_key=True); user_id:Mapped[int]=mapped_column(ForeignKey('users.id')); kind:Mapped[str]=mapped_column(String(60)); message:Mapped[str]=mapped_column(Text); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class InventoryItem(Base):
 __tablename__='inventory_items'; id:Mapped[int]=mapped_column(primary_key=True); user_id:Mapped[int]=mapped_column(ForeignKey('users.id')); name:Mapped[str]=mapped_column(String(160)); remaining_percent:Mapped[float]=mapped_column(Float,default=100); quantity_text:Mapped[str]=mapped_column(String(100),default=''); updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class FamilyMember(Base):
 __tablename__='family_members'; id:Mapped[int]=mapped_column(primary_key=True); user_id:Mapped[int]=mapped_column(ForeignKey('users.id')); name:Mapped[str]=mapped_column(String(120)); role:Mapped[str]=mapped_column(String(80))
